spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

okta.oauth2.issuer=${okta.oauth2.issuer}
okta.oauth2.client-id=${okta.oauth2.client-id}
okta.oauth2.client-secret=${okta.oauth2.client-secret}

okta.cloudinary.cloud-name=${okta.cloudinary.cloud-name}
okta.cloudinary.api-key=${okta.cloudinary.api-key}
okta.cloudinary.api-secret=${okta.cloudinary.api-secret}

spotify.client-id=${spotify.client-id}
spotify.client-secret=${spotify.client-secret}
spotify.authorize-url=${spotify.authorize-url}
spotify.token-url=${spotify.token-url}
spotify.api-base-url=${spotify.api-base-url}
spotify.redirect-uri=${spotify.redirect-uri}